// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: mcenter/apps/line/pb/rpc.proto

package line

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryLineByNamespaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 设备分配的空间
	// @gotags: bson:"namespace" json:"namespace"
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace" bson:"namespace"`
	// 设备分配的域
	// @gotags: bson:"domain" json:"domain"
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain" bson:"domain"`
}

func (x *QueryLineByNamespaceRequest) Reset() {
	*x = QueryLineByNamespaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLineByNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLineByNamespaceRequest) ProtoMessage() {}

func (x *QueryLineByNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLineByNamespaceRequest.ProtoReflect.Descriptor instead.
func (*QueryLineByNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_line_pb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *QueryLineByNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryLineByNamespaceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type LineByNamespaceSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"items" json:"items"
	Items []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items" bson:"items"`
}

func (x *LineByNamespaceSet) Reset() {
	*x = LineByNamespaceSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineByNamespaceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineByNamespaceSet) ProtoMessage() {}

func (x *LineByNamespaceSet) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineByNamespaceSet.ProtoReflect.Descriptor instead.
func (*LineByNamespaceSet) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_line_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *LineByNamespaceSet) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateLineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 设备分配的域
	// @gotags: bson:"domain" json:"domain"
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain" bson:"domain"`
	// 设备分配的空间
	// @gotags: bson:"namespace" json:"namespace"
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace" bson:"namespace"`
	// 资源名称
	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name" bson:"name"`
	// 资源ID
	// @gotags: bson:"line_id" json:"line_id"
	LineId string `protobuf:"bytes,4,opt,name=line_id,json=lineId,proto3" json:"line_id" bson:"line_id"`
	// 归属人
	// @gotags: bson:"owner" json:"owner"
	Owner string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner" bson:"owner"`
}

func (x *CreateLineRequest) Reset() {
	*x = CreateLineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLineRequest) ProtoMessage() {}

func (x *CreateLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLineRequest.ProtoReflect.Descriptor instead.
func (*CreateLineRequest) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_line_pb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLineRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateLineRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateLineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *CreateLineRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type DeleteLinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"ids"
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids"`
}

func (x *DeleteLinesRequest) Reset() {
	*x = DeleteLinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinesRequest) ProtoMessage() {}

func (x *DeleteLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcenter_apps_line_pb_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinesRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinesRequest) Descriptor() ([]byte, []int) {
	return file_mcenter_apps_line_pb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLinesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_mcenter_apps_line_pb_rpc_proto protoreflect.FileDescriptor

var file_mcenter_apps_line_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6c,
	0x69, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x1a, 0x1f,
	0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6c, 0x69, 0x6e,
	0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x53, 0x0a, 0x1b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x8c, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22,
	0x26, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0xf5, 0x01, 0x0a, 0x03, 0x52, 0x50, 0x43, 0x12,
	0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1f, 0x2e,
	0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65,
	0x73, 0x12, 0x20, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69,
	0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x12, 0x63, 0x0a, 0x14, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x29, 0x2e, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x4c, 0x69, 0x6e,
	0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x61,
	0x61, 0x7a, 0x6a, 0x2f, 0x6d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x73,
	0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcenter_apps_line_pb_rpc_proto_rawDescOnce sync.Once
	file_mcenter_apps_line_pb_rpc_proto_rawDescData = file_mcenter_apps_line_pb_rpc_proto_rawDesc
)

func file_mcenter_apps_line_pb_rpc_proto_rawDescGZIP() []byte {
	file_mcenter_apps_line_pb_rpc_proto_rawDescOnce.Do(func() {
		file_mcenter_apps_line_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcenter_apps_line_pb_rpc_proto_rawDescData)
	})
	return file_mcenter_apps_line_pb_rpc_proto_rawDescData
}

var file_mcenter_apps_line_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mcenter_apps_line_pb_rpc_proto_goTypes = []interface{}{
	(*QueryLineByNamespaceRequest)(nil), // 0: mcenter.line.QueryLineByNamespaceRequest
	(*LineByNamespaceSet)(nil),          // 1: mcenter.line.LineByNamespaceSet
	(*CreateLineRequest)(nil),           // 2: mcenter.line.CreateLineRequest
	(*DeleteLinesRequest)(nil),          // 3: mcenter.line.DeleteLinesRequest
	(*Line)(nil),                        // 4: mcenter.line.Line
	(*LineSet)(nil),                     // 5: mcenter.line.LineSet
}
var file_mcenter_apps_line_pb_rpc_proto_depIdxs = []int32{
	2, // 0: mcenter.line.RPC.CreateLine:input_type -> mcenter.line.CreateLineRequest
	3, // 1: mcenter.line.RPC.DeleteLines:input_type -> mcenter.line.DeleteLinesRequest
	0, // 2: mcenter.line.RPC.QueryLineByNamespace:input_type -> mcenter.line.QueryLineByNamespaceRequest
	4, // 3: mcenter.line.RPC.CreateLine:output_type -> mcenter.line.Line
	5, // 4: mcenter.line.RPC.DeleteLines:output_type -> mcenter.line.LineSet
	1, // 5: mcenter.line.RPC.QueryLineByNamespace:output_type -> mcenter.line.LineByNamespaceSet
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcenter_apps_line_pb_rpc_proto_init() }
func file_mcenter_apps_line_pb_rpc_proto_init() {
	if File_mcenter_apps_line_pb_rpc_proto != nil {
		return
	}
	file_mcenter_apps_line_pb_line_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mcenter_apps_line_pb_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLineByNamespaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcenter_apps_line_pb_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineByNamespaceSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcenter_apps_line_pb_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcenter_apps_line_pb_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcenter_apps_line_pb_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcenter_apps_line_pb_rpc_proto_goTypes,
		DependencyIndexes: file_mcenter_apps_line_pb_rpc_proto_depIdxs,
		MessageInfos:      file_mcenter_apps_line_pb_rpc_proto_msgTypes,
	}.Build()
	File_mcenter_apps_line_pb_rpc_proto = out.File
	file_mcenter_apps_line_pb_rpc_proto_rawDesc = nil
	file_mcenter_apps_line_pb_rpc_proto_goTypes = nil
	file_mcenter_apps_line_pb_rpc_proto_depIdxs = nil
}
