// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.1
// source: mcenter/apps/line/pb/rpc.proto

package line

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RPC_CreateLine_FullMethodName           = "/mcenter.line.RPC/CreateLine"
	RPC_DeleteLines_FullMethodName          = "/mcenter.line.RPC/DeleteLines"
	RPC_QueryLineByNamespace_FullMethodName = "/mcenter.line.RPC/QueryLineByNamespace"
)

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	CreateLine(ctx context.Context, in *CreateLineRequest, opts ...grpc.CallOption) (*Line, error)
	DeleteLines(ctx context.Context, in *DeleteLinesRequest, opts ...grpc.CallOption) (*LineSet, error)
	QueryLineByNamespace(ctx context.Context, in *QueryLineByNamespaceRequest, opts ...grpc.CallOption) (*LineByNamespaceSet, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) CreateLine(ctx context.Context, in *CreateLineRequest, opts ...grpc.CallOption) (*Line, error) {
	out := new(Line)
	err := c.cc.Invoke(ctx, RPC_CreateLine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DeleteLines(ctx context.Context, in *DeleteLinesRequest, opts ...grpc.CallOption) (*LineSet, error) {
	out := new(LineSet)
	err := c.cc.Invoke(ctx, RPC_DeleteLines_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) QueryLineByNamespace(ctx context.Context, in *QueryLineByNamespaceRequest, opts ...grpc.CallOption) (*LineByNamespaceSet, error) {
	out := new(LineByNamespaceSet)
	err := c.cc.Invoke(ctx, RPC_QueryLineByNamespace_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	CreateLine(context.Context, *CreateLineRequest) (*Line, error)
	DeleteLines(context.Context, *DeleteLinesRequest) (*LineSet, error)
	QueryLineByNamespace(context.Context, *QueryLineByNamespaceRequest) (*LineByNamespaceSet, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) CreateLine(context.Context, *CreateLineRequest) (*Line, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLine not implemented")
}
func (UnimplementedRPCServer) DeleteLines(context.Context, *DeleteLinesRequest) (*LineSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLines not implemented")
}
func (UnimplementedRPCServer) QueryLineByNamespace(context.Context, *QueryLineByNamespaceRequest) (*LineByNamespaceSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLineByNamespace not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_CreateLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).CreateLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_CreateLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).CreateLine(ctx, req.(*CreateLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DeleteLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DeleteLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_DeleteLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DeleteLines(ctx, req.(*DeleteLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_QueryLineByNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLineByNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryLineByNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPC_QueryLineByNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryLineByNamespace(ctx, req.(*QueryLineByNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcenter.line.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLine",
			Handler:    _RPC_CreateLine_Handler,
		},
		{
			MethodName: "DeleteLines",
			Handler:    _RPC_DeleteLines_Handler,
		},
		{
			MethodName: "QueryLineByNamespace",
			Handler:    _RPC_QueryLineByNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcenter/apps/line/pb/rpc.proto",
}
